// Generated by gencpp from file giskard_high/FollowPathRequest.msg
// DO NOT EDIT!


#ifndef GISKARD_HIGH_MESSAGE_FOLLOWPATHREQUEST_H
#define GISKARD_HIGH_MESSAGE_FOLLOWPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>
#include <suturo_std_msgs/BodyGroup.h>

namespace giskard_high
{
template <class ContainerAllocator>
struct FollowPathRequest_
{
  typedef FollowPathRequest_<ContainerAllocator> Type;

  FollowPathRequest_()
    : path()
    , group()  {
    }
  FollowPathRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , group(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef  ::suturo_std_msgs::BodyGroup_<ContainerAllocator>  _group_type;
  _group_type group;




  typedef boost::shared_ptr< ::giskard_high::FollowPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::giskard_high::FollowPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FollowPathRequest_

typedef ::giskard_high::FollowPathRequest_<std::allocator<void> > FollowPathRequest;

typedef boost::shared_ptr< ::giskard_high::FollowPathRequest > FollowPathRequestPtr;
typedef boost::shared_ptr< ::giskard_high::FollowPathRequest const> FollowPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::giskard_high::FollowPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::giskard_high::FollowPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace giskard_high

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'suturo_std_msgs': ['/home/adrian/suturo_ws/src/suturo_msgs/suturo_std_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::giskard_high::FollowPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::giskard_high::FollowPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::giskard_high::FollowPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4f75ba501c083c05bf4264e1844fe12";
  }

  static const char* value(const ::giskard_high::FollowPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4f75ba501c083c0ULL;
  static const uint64_t static_value2 = 0x5bf4264e1844fe12ULL;
};

template<class ContainerAllocator>
struct DataType< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "giskard_high/FollowPathRequest";
  }

  static const char* value(const ::giskard_high::FollowPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray path\n\
suturo_std_msgs/BodyGroup group\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: suturo_std_msgs/BodyGroup\n\
uint8 value\n\
\n\
uint8 NONE     = 0\n\
uint8 RIGHTARM = 1\n\
uint8 LEFTARM  = 2\n\
uint8 ALLARMS  = 3\n\
";
  }

  static const char* value(const ::giskard_high::FollowPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.group);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FollowPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::giskard_high::FollowPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::giskard_high::FollowPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "group: ";
    s << std::endl;
    Printer< ::suturo_std_msgs::BodyGroup_<ContainerAllocator> >::stream(s, indent + "  ", v.group);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GISKARD_HIGH_MESSAGE_FOLLOWPATHREQUEST_H
