// Generated by gencpp from file giskard_msgs/WholeBodyPositionGoal.msg
// DO NOT EDIT!


#ifndef GISKARD_MSGS_MESSAGE_WHOLEBODYPOSITIONGOAL_H
#define GISKARD_MSGS_MESSAGE_WHOLEBODYPOSITIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace giskard_msgs
{
template <class ContainerAllocator>
struct WholeBodyPositionGoal_
{
  typedef WholeBodyPositionGoal_<ContainerAllocator> Type;

  WholeBodyPositionGoal_()
    : left_ee_goal()
    , right_ee_goal()  {
    }
  WholeBodyPositionGoal_(const ContainerAllocator& _alloc)
    : left_ee_goal(_alloc)
    , right_ee_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _left_ee_goal_type;
  _left_ee_goal_type left_ee_goal;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _right_ee_goal_type;
  _right_ee_goal_type right_ee_goal;




  typedef boost::shared_ptr< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WholeBodyPositionGoal_

typedef ::giskard_msgs::WholeBodyPositionGoal_<std::allocator<void> > WholeBodyPositionGoal;

typedef boost::shared_ptr< ::giskard_msgs::WholeBodyPositionGoal > WholeBodyPositionGoalPtr;
typedef boost::shared_ptr< ::giskard_msgs::WholeBodyPositionGoal const> WholeBodyPositionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace giskard_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'giskard_msgs': ['/home/adrian/bachelor_thesis/ws/src/giskard_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "782548e8941cb7f36e7e0820685c913e";
  }

  static const char* value(const ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x782548e8941cb7f3ULL;
  static const uint64_t static_value2 = 0x6e7e0820685c913eULL;
};

template<class ContainerAllocator>
struct DataType< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "giskard_msgs/WholeBodyPositionGoal";
  }

  static const char* value(const ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped left_ee_goal\n\
geometry_msgs/PoseStamped right_ee_goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_ee_goal);
      stream.next(m.right_ee_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WholeBodyPositionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::giskard_msgs::WholeBodyPositionGoal_<ContainerAllocator>& v)
  {
    s << indent << "left_ee_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.left_ee_goal);
    s << indent << "right_ee_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.right_ee_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GISKARD_MSGS_MESSAGE_WHOLEBODYPOSITIONGOAL_H
